server:
  port: 36000
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    rabbit:
      enabled: false
spring:
  cloud:
    stream:
      bindings:
        oneMinuteOutput:
          destination: mmc.schedule
        oneMinuteInput:
          destination: mmc.schedule
          group: one-minute
        input:
          destination: mmc.schedule
          group: polling
      rabbit:
        bindings:
          input.consumer:
            exchangeType: direct
            bindingRoutingKey: polling
          oneMinuteOutput.producer:
            exchangeType: direct
            routingKeyExpression: '''one-minute'''
          oneMinuteInput.consumer:
            autoBindDlq: true
            ttl: 60000
            exchangeType: direct
            bindingRoutingKey: one-minute
            deadLetterExchange: mmc.schedule
            deadLetterQueueName: mmc.schedule.polling
#            deadLetterRoutingKey:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: 106.15.47.205:5672
                username: guest
                password: guest
                virtual-host: /mmc-dev
      default-binder: rabbit


